[Order-API/Order-Api] 주문 로직 수정
f-lab-edu/health-plus pull request #52
Opened 2022-12-24 12:39 UTC by vellatrix

## 개요
- 클래스 정리 및 메소드 시그니처 변경

## 작업 사항
- 위와 동일

2022-12-24 16:34 UTC, f-lab-lyan commented on order-api/src/main/java/org/healthplus/order/domain/entity/Order.java
> +    this.id = orderId;
```suggestion
    this(orderId, null);
```
이 좀 더 나을 것 같네요.

2022-12-24 16:40 UTC, f-lab-lyan commented on order-api/src/main/java/org/healthplus/order/domain/entity/Order.java
> +  public Order(Long orderId) {
Order를 생성할 수 있는 방법이 너무 많은 것 같아요. 물론, 각각이 필요한 이유가 있겠지만, 이렇게 되면 나중에 order를 생성해야할 경우, 어떤 걸 써야할지 혼란 스러울 수 있을 것 같습니다.

2022-12-24 16:46 UTC, f-lab-lyan commented on order-api/src/main/java/org/healthplus/order/presentation/dto/OrderCreationResponse.java
> +  private List<String> menuName;
이 값을 List<String> 으로 한 특별한 이유가 있을까요? Map<String, String> 으로 하면 client에서 해석하기도 편하고, 우리쩍에서도 String.format같은 걸 하지 않고 보낼 수 있지 않을까요?

2022-12-24 16:47 UTC, f-lab-lyan commented on payment-api/build.gradle
> +
nit: Please remove these two lines.

2022-12-25 03:13 UTC, f-lab-lyan commented on order-api/src/main/java/org/healthplus/order/domain/entity/Order.java
> +  public void startOrder() {
```suggestion
  public void setOrdered() {
```

2022-12-25 03:14 UTC, f-lab-lyan commented on order-api/src/main/java/org/healthplus/order/domain/entity/Order.java
> +  public void startOrder() {
로직만 보면 `setOrdered`가 더 좋아보이는데, 아래의 내용들을 보니, `makeOrder`정도의 의미인것 같은데 어떠세요?

2022-12-25 03:17 UTC, f-lab-lyan commented on order-api/src/main/java/org/healthplus/order/domain/entity/Order.java
> +    raiseEvent(OrderPaidEvent.toEvent(this));
이 부분은 지금 고민할 필요가 없어 보이긴 하지만, 만약에 event를 핸들링하는 코드가 다른 인스턴스에 있는 경우에는 this를 넘기는 것이 가능할 수도 있고, 불가능할 수도 있어서, 여기서 명시적으로 this의 내용을 복사해서 넘기는 것이 더 좋아보입니다.

2022-12-25 03:18 UTC, f-lab-lyan commented on order-api/src/main/java/org/healthplus/order/domain/event/OrderCanceledEvent.java
> +
nit: Please remove this line

2022-12-25 03:31 UTC, f-lab-lyan commented on order-api/src/main/java/org/healthplus/order/domain/event/OrderPaidEvent.java
> +  public OrderPaidEvent(Long orderId,
Builder를 이렇게 쓰시면, OrderPaidEvent를 만들 수 있는 방식이

```
OrderPaidEvent ope = new OrderPaidEvent(...);
OrderPaidEvent ope2 = new OrderPaidEvent.OrderPaidEventBuild()....build();
```
이렇게 두 가지가 되는데, 이것보다는 한가지로 통일하는게 좋을 것 같습니다. 그리고 밑에 `toEvent(Order order)`라는 static 메소스도 있는데, 이 중에 어떤 걸 쓰려는 의도인지 파악하기 힘들 것 같습니다. 태훈님의 원래 의도는 어떻게 생성하는 것이었나요? 그것에 맞춰서 코드를 수정하는게 좋을 것 같습니다.

2022-12-25 03:32 UTC, f-lab-lyan requested changes
아마도 코드 리팩토링 느낌이었을 것 같은데, 몇 가지 코멘트를 추가하였습니다. 확인 부탁 드립니다.

2022-12-25 05:22 UTC, vellatrix commented on order-api/src/main/java/org/healthplus/order/domain/entity/Order.java
> +    this.id = orderId;
조언 감사드립니다.
보여주신 방법 보다가 떠오른 건데
혹시, public static 메소드를 만들어서 그 안에 생성자를 Private으로 만들고 처리하는 것도 괜찮은 방법일까요?

2022-12-25 05:26 UTC, vellatrix commented on order-api/src/main/java/org/healthplus/order/domain/entity/Order.java
> +  public void startOrder() {
의미가 더 명확하다고 생각합니다.
감사합니다.

2022-12-25 05:34 UTC, vellatrix commented on order-api/src/main/java/org/healthplus/order/presentation/dto/OrderCreationResponse.java
> +  private List<String> menuName;
백엔드에서 처리해서 프론트단에서 가공할 필요 없게 하려는 목적으로 만들었습니다.
말씀하신 Map 방법도 되게 좋다고 생각합니다.

2022-12-25 05:36 UTC, vellatrix commented on payment-api/build.gradle
> +
아직 Payment 모듈에 존재하는 ResttemplateConfig 클래스를 커밋하지 않았는데,
혹시 사용할 목적이 있더라도, Payment 모듈내에 추가하는 게 합리적이지 않은 방법일까요?

2022-12-25 05:52 UTC, vellatrix commented on order-api/src/main/java/org/healthplus/order/domain/entity/Order.java
> +    raiseEvent(OrderPaidEvent.toEvent(this));
죄송하지만, 말씀하신 
"**만약에 event를 핸들링하는 코드가 다른 인스턴스에 있는 경우에는 this를 넘기는 것이 
가능할 수도 있고, 불가능할 수도 있어서**"
이 부분이 잘 이해가 가지 않았습니다.
혹시, 조금 더 상세하게 설명 부탁드려도 될까요?

2022-12-25 05:56 UTC, vellatrix commented on order-api/src/main/java/org/healthplus/order/domain/event/OrderPaidEvent.java
> +  public OrderPaidEvent(Long orderId,
넵 말씀하신대로 한 가지로 통일해서 사용하겠습니다.
제 원래 의도는 생성자에 @Builder 를 붙여서 그 생성자를 static toEvent()에서 사용하려는 것이였습니다.
만들어놓고 보니, 하나로 만드는 게 맞다고 생각합니다.

2022-12-25 06:02 UTC, merged

2022-12-25 07:36 UTC, jongyoul commented on order-api/src/main/java/org/healthplus/order/presentation/dto/OrderCreationResponse.java
> +  private List<String> menuName;
그렇군요. 저는 이건 대충 map으로 주면, 프론트(또는 앱)에서 알아서 UI로 보여주겠지? 라고 생각했었습니다. :-)

2022-12-25 07:37 UTC, f-lab-lyan commented on order-api/src/main/java/org/healthplus/order/presentation/dto/OrderCreationResponse.java
> +  private List<String> menuName;
그렇군요. 저는 이건 대충 map으로 주면, 프론트(또는 앱)에서 알아서 UI로 보여주겠지? 라고 생각했었습니다. :-)

2022-12-25 07:38 UTC, f-lab-lyan commented on payment-api/build.gradle
> +
아 // 일단 제 얘기는 빈 줄을 지워달라는 요청이었습니다. :-)

그리고 사용하기 전에 미리 추가해 두는 것보다는 해당 코드가 같이 있는 PR에 한꺼번에 올리는게 commit관리 측면에서도 좋을 것 같습니다.

2022-12-25 07:40 UTC, f-lab-lyan commented on order-api/src/main/java/org/healthplus/order/domain/entity/Order.java
> +    raiseEvent(OrderPaidEvent.toEvent(this));
아 // 지금은 이벤트 핸들러가 같은 인스턴스에서 동작하고 있기 때문에 this를 넘겨도 object reference가 잘 넘어가서 처리가 가능한데요. event핸들러를 확장해서 서로 다른 인스턴스에서 pub/sub 하게 되는 상황이 되면, this를 넘기면, 제대로된 값이 넘어가지 않을 가능성이 있다는 얘기였습니다. 혹시 잘 이해가 안되시면, 멘토링 시간에 다시 얘기해보죠. 알려주세요.

2022-12-25 07:40 UTC, f-lab-lyan commented on order-api/src/main/java/org/healthplus/order/domain/event/OrderPaidEvent.java
> +  public OrderPaidEvent(Long orderId,
네 그럼 Contructor를 private으로 만들고, static 메소드로만 해당 객체를 생성할 수 잇도록 바꾸는 게 좋을 것 같습니다.